import React from 'react'
import type { Metadata } from "next";
import {Link} from 'next/navigation' 

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
  };

function Layout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <main className="min-h-screen flex flex-row w-full justify-start items-center gap-3">
        <aside className="w-1/5 h-screen bg-main flex flex-col justify-start items-center">
          <nav className="flex flex-col gap-3">
            <Link href="/dashboard" className="text-lg font-bold">Dashboard</Link>
            <Link href="/profil" className="text-lg font-bold">Profil</Link>
            <Link href="/settings" className="text-lg font-bold">Settings</Link>
            <Link href="/help" className="text-lg font-bold">Help</Link>
          </nav>
        </aside>
        <div className="container">
          {children}
        </div>
    </main>
  )
}

export default Layout